version: "3.1"
volumes:
    sql-server-test:
services:
  sql-server-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server
    # hostname: mssql
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Fdsa@1234"
      ACCEPT_EULA: "Y"
    #   MSSQL_PID: Express
    volumes:
        - sql-server-test:/sql_data
